[package]
name = "aoc_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interior_mutability_pointer = "0.1.2"
aoc_lib = { git = "https://github.com/samhamnam/aoc_lib" }